#!/usr/bin/env bash
#
# Runs INSIDE a Fly.io Sprite. Installs single-user Nix if absent, then builds
# and activates the home-manager configuration from the flake shipped by
# scripts/provision.sh.
#
# Safe to re-run: every step is idempotent.
#
set -euo pipefail

FLAKE_DIR=${FLAKE_DIR:-$HOME/.config/home-manager}
HM_CONFIG=${HM_CONFIG:-sprite}

log() { printf '\033[1;32m==>\033[0m %s\n' "$*" >&2; }
die() { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

[ -f "$FLAKE_DIR/flake.nix" ] || die "no flake.nix in $FLAKE_DIR"

# /nix has to exist and be owned by us before the installer will do a
# single-user install.
if [ ! -d /nix ]; then
  log "creating /nix"
  if [ "$(id -u)" -eq 0 ]; then
    mkdir -m 0755 /nix
  elif command -v sudo >/dev/null 2>&1; then
    sudo mkdir -m 0755 /nix
    sudo chown "$(id -u):$(id -g)" /nix
  else
    die "need root or sudo to create /nix"
  fi
fi

if ! [ -e "$HOME/.nix-profile/etc/profile.d/nix.sh" ]; then
  # --no-daemon on purpose: the guest has no systemd to run nix-daemon under,
  # and a Sprite loses RAM (hence any daemon) on hibernation while keeping the
  # filesystem. A single-user install needs no resident process.
  log "installing single-user Nix"
  curl -fsSL https://nixos.org/nix/install |
    sh -s -- --no-daemon --no-channel-add --yes
fi

# shellcheck disable=SC1091  # generated by the installer
. "$HOME/.nix-profile/etc/profile.d/nix.sh"

command -v nix >/dev/null 2>&1 || die "nix is still not on PATH after install"

# Owned here rather than by home-manager: home.packages shares
# ~/.nix-profile with the installer's own `nix`, so letting home-manager
# manage nix.package would conflict on bin/nix at activation time.
log "writing ~/.config/nix/nix.conf"
mkdir -p "$HOME/.config/nix"
#
# The numtide substituter is required, not an optimisation: hermes-agent and
# claude-code are only cached there, and building them from source inside a
# microVM is slow. A single-user install makes us the store owner, so
# substituters in the user's nix.conf are trusted.
cat >"$HOME/.config/nix/nix.conf" <<'EOF'
experimental-features = nix-command flakes
warn-dirty = false
accept-flake-config = false
extra-substituters = https://cache.numtide.com
extra-trusted-public-keys = niks3.numtide.com-1:DTx8wZduET09hRmMtKdQDxNNthLQETkc/yaX7M4qK0g=
EOF

log "building homeConfigurations.$HM_CONFIG.activationPackage"
activation=$(
  nix build \
    --extra-experimental-features 'nix-command flakes' \
    --no-link --print-out-paths \
    "$FLAKE_DIR#homeConfigurations.$HM_CONFIG.activationPackage"
)
[ -n "$activation" ] || die "build produced no output path"

log "activating $activation"
# The Ubuntu image ships its own ~/.bashrc and ~/.profile, and home-manager
# refuses to clobber files it does not own. The activation script honours
# these variables (same mechanism as `home-manager switch -b`), so the first
# run renames them instead of aborting.
export HOME_MANAGER_BACKUP_EXT=before-home-manager
export HOME_MANAGER_BACKUP_OVERWRITE=1

"$activation/activate"

log "activated — 'sprite console' will now land in the managed shell"
